# Generated by Django 2.2.6 on 2019-10-19 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateField(help_text='Departure', verbose_name='departure')),
                ('arrival', models.DateField(help_text='Arrival', verbose_name='arrival')),
                ('simple_rooms', models.IntegerField(help_text='Simple rooms available', verbose_name='simple_rooms')),
                ('double_rooms', models.IntegerField(help_text='Double rooms available', verbose_name='double_rooms')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price', max_digits=15, verbose_name='price')),
            ],
            options={
                'ordering': ['departure'],
            },
        ),
        migrations.CreateModel(
            name='Travelers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.TextField(help_text='First Name', verbose_name='f_name')),
                ('l_name', models.TextField(help_text='Last Name', verbose_name='l_name')),
                ('suit_size', models.TextField(help_text='Suit size', verbose_name='suit_size')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(help_text='Your name', verbose_name='name')),
                ('email', models.TextField(help_text='Your email', verbose_name='email')),
                ('password', models.TextField(help_text='Your password', verbose_name='password')),
                ('birthday', models.DateField(help_text='Your birthday', verbose_name='birthday')),
                ('id_doc', models.TextField(help_text='Your document', verbose_name='id_doc')),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(help_text='Room type', verbose_name='room')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='api.User', verbose_name='Buyer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight', to='api.Flight', verbose_name='Flight')),
            ],
        ),
    ]
